branch-defaults:
  default:
    environment: Midrcapi-env-2
environment-defaults:
  Midrcapi-env:
    branch: null
    repository: null
global:
  application_name: MIDRC-API
  default_ec2_keyname: Django-key
  default_platform: Python 3.7 running on 64bit Amazon Linux 2
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  no-verify-ssl: true
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: null
  workspace_type: Application
